### PR TITLE
Fix flac.Decode handling of io.EOF

### PR DESCRIPTION
**Pull request by MarkKremer**
Resolves https://github.com/gopxl/beep/issues/126

Testscript I used to check the return codes are [conform the `Streamer` interface](https://github.com/gopxl/beep/blob/b7ad46ab05f55bd030a4ab067ca6e24e144d98f2/interface.go#L24C10-L24C10) below. I've not included the test in the codebase because I don't want to add another audio file to the repo.
```golang
package flac

import (
	"github.com/gopxl/beep"
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

func TestDecode(t *testing.T) {
	f, err := os.Open("path/to/file.flac")
	if err != nil {
		panic(err)
	}

	streamer, _, err := Decode(f)
	if err != nil {
		panic(err)
	}
	defer streamer.Close()

	collect(beep.Take(streamer.Len()-5, streamer))

	buf := make([][2]float64, 512)

	// Case 2: return ok with 0 < n < 512 samples
	n, ok := streamer.Stream(buf[:])
	assert.True(t, ok)
	assert.Equal(t, 5, n)

	// Case 3: return !ok with n == 0
	n, ok = streamer.Stream(buf[:])
	assert.False(t, ok)
	assert.Equal(t, 0, n)
}

// collect drains Streamer s and returns all of the samples it streamed.
func collect(s beep.Streamer) [][2]float64 {
	var (
		result [][2]float64
		buf    [479][2]float64
	)
	for {
		n, ok := s.Stream(buf[:])
		if !ok {
			return result
		}
		result = append(result, buf[:n]...)
	}
}

```

### CODE REVIEW

**Comment by duysqubix** [comment]
@MarkKremer 

Is there a way we could  mock even a simple and super small audio file so that we can inject it into the test itself? I think it's important to have these tests as part of the automated builds and tests

**Review by duysqubix — CHANGES_REQUESTED** [review]
see above

**Comment by MarkKremer** [comment]
I've been thinking about mocking the flac library itself to really test fail scenario's etc. Ofc with mocking this would make some assumptions on how the flac package works, but I think that's the best option.

**Comment by duysqubix** [comment]
I'm just thinking without having to copy over the entire library itself, the flac packaging protocol itself, we implement that ourselves and synthetically create a valid flac format string of binary that can be saved in a buffer that is passed to the 'file open'. It doesn't even have to be valid audio or an actual song or noise.. just something that is valid flac to test that the decode/encode works properly. 


I'm not very familiar with implementing audio formats, but this is a [good start](https://www.nayuki.io/page/simple-flac-implementation)?

**Comment by MarkKremer** [comment]
My original thought was mocking `flac.Stream` and it's [`ParseNext()`](https://github.com/mewkiz/flac/blob/426a7bedfecf90367f2d6d6a728dd57dea5170ae/flac.go#L311) method which returns [`flac.Frame`](https://github.com/mewkiz/flac/blob/426a7bedfecf90367f2d6d6a728dd57dea5170ae/frame/frame.go#L49C4-L49C4) which can easily be filled with whatever data we want.

We've been working on flac encoding so it's also possible to just encode some data. However, that is not possible for some of the other formats Beep supports. I think it's easier to create audio test files manually than programmatically. Audio formats can be pretty complex.

**Comment by duysqubix** [comment]
okay fair enough. I don't mind adding audio files to the repo for testing, let's try to keep them very small in size and reuse them for all tests... one for flac, one for mp3, etc...

**Comment by MarkKremer** [comment]
Thanks for keeping me sharp!

I've added a testfile and test. I've moved existing test functions into the `internal` directory so they can be used in the subpackages.

**Review by duysqubix — APPROVED** [review]

**Pull request merged**
